export const DiffMenus=[{// arreglo de los menus
    id: 'Menu-Ejecutivo',
    categoria: 'Menu Ejecutivo',
    nombre: 'Menu Ejecutivo',
    estado:'disponible',
    precio:100,
    detalle:'DE ENTRADA: bastones de queso con salsa. COMO PRINCIPAL: lomo bife de chorizo con guarnicion de ensalada . POSTRE: flan con dulce de leche',
    entrada: 'bastones de queso con salsa',
    url_entrada: 'https://i.ytimg.com/vi/BBwKKFFShII/maxresdefault.jpg',
    principal: 'lomo bife de chorizo con guarnicion de ensalada',
    url_principal:'https://www.cucinare.tv/wp-content/uploads/2019/09/Bife-con-ensalada.jpg',
    postre: 'flan con dulce de leche',
    url_postre: 'https://okdiario.com/img/2016/08/05/receta-de-flan-de-dulce-de-leche-facil-2.jpg',
    //creo que faltarian los precios
},
{
    id: 'Menu-Rustico',
    categoria: 'Menu Rustico',
    nombre: 'Menu Rustico',
    estado:'agotado',
    precio:100,
    detalle:'DE ENTRADA: 2 empanadas de carne o de pollo. COMO PRINCIPAL: milanesa caballo con pure o fritas. POSTRE: dulce de batata con chocolate y queso',
    entrada: '2 empanadas de carne o de pollo',
    url_entrada: 'https://media-cdn.tripadvisor.com/media/photo-s/09/d3/c3/b7/la-morada.jpg',
    principal: 'milanesa caballo con pure o fritas',
    url_principal:'https://media.lmneuquen.com/p/7e0c76e74c99f6ec8c82e3fb61c43116/adjuntos/195/imagenes/005/541/0005541097/1200x675/smart/milanesas-a-caballojpg.jpg',
    postre: 'dulce de batata con chocolate y queso',
    url_postre:'https://pbs.twimg.com/media/EWA2L4cXQAAVd9B.jpg',
    //creo que faltarian los precios
},
{   
    id: 'Menu-Vegetariano',
    categoria: 'Menu Vegetariano',
    nombre: 'Menu Vegetariano',
    estado:'disponible',
    precio:100,
    detalle:'DE ENTRADA:Palitos de calabacín al horno. COMO PRINCIPAL: tarta de acelga y zapallitos. POSTRE: ensalada de frutas en almibar de durazno',
    entrada: 'Palitos de calabacín al horno',
    url_entrada:'https://gastronomiaycia.republica.com/wp-content/uploads/2015/03/hct_calabacin_aromatico_bas.jpg',
    principal: 'tarta de acelga y zapallitos',
    url_principal:'https://i.pinimg.com/474x/b7/66/9b/b7669b8b0a6aff2c2866d573dc21689f.jpg',
    postre: 'ensalada de frutas en almibar de durazno',
    url_postre:'https://www.cardamomo.news/__export/1645132962171/sites/debate/img/2022/02/17/coctel_de_frutas_en_almibar.png_423682103.png',
},
]